### ISSUE TITLE
Still using this keyboard?

### ISSUE THREAD

**Issue by marwatk** [riskable/riskeyboard70#2]
After testing out the the concept I really like the tactility and am planning on building a full custom keyboard using your ideas, but I wanted to see how you're liking it after long term use before I dive in. Would you mind answering a few questions?

Are you still using it as your primary keyboard?
Any downsides you've encountered?
How's it holding up/do you find you're having to reprint pieces often?

Thanks for all the work you've done!

**Comment by riskable** [comment]
Yes I'm still using it as my primary keyboard!  Best keyboard I've ever owned/typed on (seriously, I love this thing!)

Only downside is that the layer lines on the 3D printed keycaps tend to pick up finger cheese a bit faster than regular keycaps.  That was something I predicted though which is why I made it so damned easy to take the top off the keyboard, clean it in the sink, then return it back to the keyboard *while it's still a little wet* and get back to typing 👍.  Of course, you wouldn't have that problem if you used injection molded keycaps.

I have yet to have to re-print anything at all.  Everything's holding up just fine after about nine months of typing extensively on this thing every day (because I use it for work).  That said, I had to make new stabilizer wires for the Enter and Backspace keys shortly after I put it together because they were getting stuck down (was annoying TF out of me haha).  They've been fine ever since I *very carefully* bent new wires and put them in place.

Aside: I actually have a great new 3D printable wire bending tool that makes perfect stabilizer bars out of 18 gauge stainless steel wire every time (it's really hard to get it perfect without a lot of fiddling otherwise) 👍

**Comment by marwatk** [comment]
Thanks for the response! My test keys feel awesome so I'm happy to hear I stays that way. I'm not as pure as you, though, and am definitely going the injection molded key-cap route. :stuck_out_tongue_closed_eyes: 

Guess it's time to dive in!

-Marcus

**Comment by modx-arseniy** [comment]
Any plans for lowprofile 68+% foldable or split ortolinear kb? 

Nrf52 or others 2.4/bt/wired?

(+1 think not seen in retail kb: 
changing backlight mode for different languages. Something +- like that: https://habr.com/ru/articles/651317)


-------------------------------------------------
(Now testing my first mech kb K539/k621 Redragon Anubis/Horus, brown Outemu low profIle/red Outemu low profile. Brown Anubis switches - s***, IMHO(too often double click, too easily tapes...). Red+- ok, and Horus's pbt/abs keycaps better. 

(Booth on "updated&newly" byk916 8bit s*** 80's Intel 8051 mcu clone, lol. There were powerful "outdated" sonic 32(?) bit mcu before in their old kbs, and even SonixQMK&OpenRGB ported! Maybe Redragon's changIng to SO prehistoric mcu cousing That QMK ports. Dates +- 1:1)  

Waiting delivery of old used k552 tkl for testing QMK+OpenRGB. There were high expectations from the opportunity to set up something like that ((on habr  - Corsair software diy module/also in Linux something opensourse), or maybe This https://www.ixbt.com/peripheral/logitech-g11-ruslight.shtml Diy led mod in comments)

+Needed test 80g, 100g--150+g springs. Especially for those brown switchs. For now that keyboard almost unusable(.

Diy magnetic Hall effect KB - Awesome Project! Looks like the next goal, It would be great to repeat something like this with minor changes when decide on the shape, size, etc.
